#!/bin/sh
# description "fetch SSH keys"
# author "Online Labs Cloud Team <cloud-team@labs.online.net>"

set -e

/usr/local/bin/oc-metadata --cached | grep SSH_PUBLIC_KEYS_.*_KEY | cut -d'=' -f 2- | tr -d \' > /root/.ssh/authorized_keys
