#! /bin/sh
### BEGIN INIT INFO
# Provides:          disconnectnbd
# Required-Start:
# Required-Stop:
# Default-Start:
# Default-Stop:      6
# X-Stop-After: umountroot
# Short-Description: Disconnect nbd root device
# Description:
### END INIT INFO

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
. /lib/init/vars.sh

. /lib/lsb/init-functions

umask 022

case "$1" in
  start)
    # No-op
    ;;
  stop)
    log_daemon_msg "Disconnect nbd root volume"
    if [ -x /usr/sbin/nbd-disconnect-root ]; then
      /usr/sbin/nbd-disconnect-root
    fi
    ;;
  restart|reload|force-reload)
    echo "$NAME does not support restarting." >&2
    exit 1
    ;;
  *)
    echo "Usage: $0 start|stop" >&2
    exit 1
    ;;
esac

:
