#!/bin/bash

export PATH="${PATH:+$PATH:}/bin:/usr/bin:/usr/local/bin"

[ -r /etc/lsb-release ] && . /etc/lsb-release

if [ -z "$DISTRIB_DESCRIPTION" ] && [ -x /usr/bin/lsb_release ]; then
	# Fall back to using the very slow lsb_release utility
	DISTRIB_DESCRIPTION=$(lsb_release -s -d)
fi

[ -r /etc/scw-release ] && . /etc/scw-release

metadata() {
  oc-metadata --cached "$1"
}

volume_metadata() {
  device=$1
  key=$2
  metadata VOLUMES_${device}_${key}
}

INTERNAL_IP=$(/sbin/ifconfig eth0 | grep 'inet addr:' | cut -d: -f2 | awk '{ print $1}')

KERNEL_VERSION=$(uname -r)
if [[ $KERNEL_VERSION =~ ^3\.1[78]\.[0-9]+-[0-9]+ ]]; then
    KERNEL_TITLE="- Mainline"
    KERNEL_DESCRIPTION="This kernel has more features and plenty of modules"
    KERNEL_SUGGESTION="For greater performances, use the Marvell 3.2.34 kernel instead"
fi
if [[ $KERNEL_VERSION =~ ^3\.2\.[35][24].* ]]; then
    KERNEL_TITLE="- Marvell (Proprietary)"
    KERNEL_DESCRIPTION="This kernel has the best performances on this hardware"
    KERNEL_SUGGESTION="For mainline kernel with latest features and plenty of modules, use a 3.17 kernel instead"
fi

cat<<EOF

Welcome on $IMAGE_DESCRIPTION on Scaleway' C1.

 * Kernel:           $(uname -o) $(uname -r) $(uname -m) $KERNEL_TITLE
EOF
if [ "$KERNEL_DESCRIPTION" != "" ]; then echo "                     - $KERNEL_DESCRIPTION"; fi
if [ "$KERNEL_SUGGESTION" != "" ]; then echo "                     - $KERNEL_SUGGESTION"; fi


cat<<EOF
 * Distribution:     $IMAGE_DESCRIPTION ($IMAGE_RELEASE) on $DISTRIB_DESCRIPTION
 * Internal ip:      $INTERNAL_IP
 * External ip:      $(metadata PUBLIC_IP_ADDRESS)
EOF

for i in {0..16}; do
  metadata VOLUMES_${i} | grep " " >/dev/null || continue

  SIZE=$(( $(volume_metadata $i SIZE) / 1000 / 1000 / 1000 ))G
  echo " * Disk /dev/nbd${i}:   $(volume_metadata $i NAME) ($(volume_metadata $i VOLUME_TYPE) ${SIZE})"
done

lsmod | grep nolp >/dev/null && \
	echo " * NOLP.ko module:   Running"

echo " * Uptime:          $(/usr/bin/uptime)"

cat<<EOF

Links
 * Documentation:    $IMAGE_DOC_URL
 * Community:        $IMAGE_HELP_URL
 * Image source:     $IMAGE_SOURCE_URL
EOF
