#!/bin/sh

### BEGIN INIT INFO
# Provides:		nbd-disconnect-root
# Required-Start:
# Required-Stop:
# X-Stop-After:		umountroot
# Default-Start:
# Default-Stop:         0 6
# Short-Description:NBD disconnect root
### END INIT INFO

. /lib/lsb/init-functions

set -e

nbddisconnectroot_stop() {
    if [ -x /usr/local/sbin/oc-nbd-disconnect-root ]; then
	log_action_begin_msg "Disconnecting root NBD device and rebooting"
        /usr/local/sbin/oc-nbd-disconnect-root
	log_action_end_msg 0
    fi
}

export PATH="${PATH:+$PATH:}/usr/sbin:/sbin"

case "$1" in
  stop)
	nbddisconnectroot_stop
	;;
  *)
	log_action_msg "Usage: /etc/init.d/nbd-root-disconnect stop" || true
	exit 1
esac

exit 0
