#!/bin/bash

# This script will prepare the rootfs for the image-builder toolsuite

set -e

# prevent init scripts from running during install/update
printf '#!/bin/sh\nexit 101\n' > /usr/sbin/policy-rc.d && chmod +x /usr/sbin/policy-rc.d
if [ -f /sbin/initctl.distrib ]; then
    mv /sbin/initctl.distrib /sbin/initctl
fi
cp /sbin/initctl /sbin/initctl.orig
printf '#!/bin/sh\nexit 0\n' > /sbin/initctl
dpkg-divert --local --rename --add /sbin/initctl
