#!/bin/sh
# description "disconnect extra NBD volumes"
# author "Scaleway <opensource@scaleway.com>"

XNBD_CLIENT=/run/initramfs/usr/sbin/xnbd-client

for device in /dev/nbd[!0]*
do
    ($XNBD_CLIENT -c $device && $XNBD_CLIENT -d $device > /dev/null 2>&1) || true
done
