#!/usr/bin/env ash

export PATH="${PATH:+$PATH:}/bin:/usr/bin:/usr/local/bin"

[ -r /etc/lsb-release ] && . /etc/lsb-release
[ -r /etc/scw-release ] && . /etc/scw-release
if [ -z "$DISTRIB_DESCRIPTION" ] && [ -x /usr/bin/lsb_release ]; then
    # Fall back to using the very slow lsb_release utility
    DISTRIB_DESCRIPTION=$(lsb_release -s -d)
fi

date=`date`
ip=`ifconfig $(route | grep default | awk '{ print $8 }') | grep "inet addr" | awk -F: '{print $2}' | awk '{print $1}'`
public_ip=$(scw-metadata --cached PUBLIC_IP_ADDRESS)

metadata() {
  scw-metadata --cached "$1"
}

volume_metadata() {
  device=$1
  key=$2
  scw-metadata --cached "VOLUMES_${device}_${key}"
}


KERNEL_VERSION=$(uname -r)

[ -f /etc/motd.head ] && cat /etc/motd.head || true
printf "\n"
printf "Welcome on %s (%s %s %s %s)\n" "${IMAGE_DESCRIPTION}" "$(uname -o)" "${KERNEL_VERSION}" "$(uname -m)" "$KERNEL_TITLE"
printf "\n"
printf "System information as of: %s (boot time)\n" "$date"
printf "\n"
printf "Int IP Address:\t%s\tPub IP Address:\t%s\n" $ip $public_ip
printf "Image build:\t%s\n" "${IMAGE_RELEASE}"

for i in {0..16}; do
  metadata VOLUMES_${i} | grep " " >/dev/null || continue

  SIZE=$(( $(volume_metadata $i SIZE) / 1000 / 1000 / 1000 ))G

  volume_export_uri="$(volume_metadata $i EXPORT_URI)"
  if [ "$(echo "$volume_export_uri" | cut -d: -f1)" = "nbd" ]; then
    device_name="nbd$i"
  else
    device_name="$(echo "$volume_export_uri" | sed s@device://dev/@@)"
  fi
  printf "Disk %s:\t%s\n" "$device_name" "$(volume_metadata $i VOLUME_TYPE) ${SIZE}"
done
printf "\n"

printf "Documentation:\t%s\n" "$IMAGE_DOC_URL"
printf "Community:\t%s\n" "$IMAGE_HELP_URL"
printf "Image source:\t%s\n" "$IMAGE_SOURCE_URL"
printf "\n"
[ -f /etc/motd.tail ] && cat /etc/motd.tail || true
