#!/bin/sh
# Thanks to the LTSP project
# If the root /dev/nbd0 device is unmounted on reboot then nbd read
# errors occur, and if it isn't, then # the nbd-server process on the server
# doesn't terminate.
# Called by init scripts on reboot.

case "$RUNLEVEL" in
    6)
        key="b"
        ;;
    *)
        echo "oc-nbd-disconnect-root should only be called by initscripts on reboot." >&2
        exit 1
        ;;
esac

if [ -e /usr/local/sbin/xnbd-client ]; then
    NBD_CLIENT=/usr/local/sbin/xnbd-client
elif [ -e /usr/sbin/xnbd-client ]; then
    NBD_CLIENT=/usr/sbin/xnbd-client
else
    NBD_CLIENT=/sbin/nbd-client
fi

disconnect() {
    $NBD_CLIENT -d "$root"
    echo "$key" > /proc/sysrq-trigger
}

# Disconnect swap nbd devices first
while read device etc; do
    case "$device" in
        /dev/nbd[0-9])
            if [ "device" = "/dev/nbd0" ]; then
                # do not disconnect non-existing device (rescue)
                pgrep -f '@xnbd-client.*/dev/nbd0' >/dev/null || continue
            fi
            swapoff "$device"
            $NBD_CLIENT -d "$device"
            ;;
        /dev/mapper/swap[0-9])
            nbd_device=$(cryptsetup status "$device" | awk '/device:/{print $2}')
            swapoff "$device"
            cryptsetup remove "$device"
            case "$nbd_device" in
                /dev/nbd[1-9])
                    $NBD_CLIENT -d "$nbd_device"
                    ;;
            esac
            ;;
    esac
done < /proc/swaps

unset root
for param in $(cat /proc/cmdline); do
    case "$param" in
        root=/dev/nbd[0-9])
            root="${param#root=}"
            ;;
    esac
done
test -n "$root" || exit 0
disconnect
