#!/bin/bash
# description "disconnect root NBD volume"
# author "Scaleway <opensource@scaleway.com>"

XNBD_CLIENT=/run/initramfs/usr/sbin/xnbd-client

$XNBD_CLIENT -d "$root"
echo "b" > /proc/sysrq-trigger
