#!/bin/sh

if [ "$1" = "" ]; then
    oc-metadata --cached | grep "^TAGS_" | cut -d'=' -f2-3
    exit 0
fi

VALUE=$(oc-metadata --cached | grep "^TAGS_" | cut -d'=' -f2-3 | grep "^$1")
VALUE1=$(echo $VALUE | awk -F'=' '{print $1}')
VALUE2=$(echo $VALUE | awk -F'=' '{print $2}')
if [ "$VALUE1" = "" ]; then
    echo "0"
    exit 1
fi
if [ "$VALUE2" = "" ]; then
    echo "1"
else
    echo $VALUE2
fi
exit 0
