#!/bin/bash
# description "disconnect root NBD volume"
# author "Scaleway <opensource@scaleway.com>"

XNBD_CLIENT=/run/initramfs/usr/sbin/xnbd-client
$XNBD_CLIENT --version &> /dev/null
$XNBD_CLIENT -d /dev/nbd0
echo "b" > /proc/sysrq-trigger
