#!/bin/sh
# description "generate a unique machine id"
# author "Scaleway <opensource@scaleway.com>"

if [ -f /etc/.regen-machine-id ]
then
	uuidgen > /etc/machine-id
	rm -f /etc/.regen-machine-id
fi
